services:
  postgres:
    image: postgres@sha256:aedabd10a05c7304233d006a186a42d7d350b11e702d227dc09a99882dafa142
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: campaign_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d campaign_dev -h postgres -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis@sha256:cc2dfb8f5151da2684b4a09bd04b567f92d07591d91980eb3eca21df07e12760
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
