name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test & Typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 25
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: campaign_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 2s --health-timeout 2s --health-retries 30
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" --health-interval 2s --health-timeout 2s --health-retries 30
    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/campaign_dev
      REDIS_URL: redis://127.0.0.1:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.17.1 --activate

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-v1-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-v1-

      - name: Configure pnpm store path
        run: pnpm config set store-dir ~/.pnpm-store

      - name: Configure .npmrc (GitHub Packages if needed)
        run: |
          echo "@returnacy:registry=https://npm.pkg.github.com/" > .npmrc || true
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc || true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        working-directory: db
        run: pnpm prisma generate --schema=./prisma/schema.prisma

      - name: Apply migrations (deploy)
        working-directory: db
        run: pnpm prisma migrate deploy --schema=./prisma/schema.prisma

      - name: Build packages
        run: |
          pnpm --filter @campaign-service/db build
          pnpm --filter @campaign-service/scheduler build
          pnpm --filter @campaign-service/server build

      - name: Typecheck
        run: pnpm -r exec tsc --noEmit --pretty false --skipLibCheck

      - name: Run tests
        run: pnpm test
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          REDIS_URL: ${{ env.REDIS_URL }}

  docker:
    name: Build Docker Images
    needs: test
    if: needs.test.result == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [server, scheduler]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.service }} Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service }}/Dockerfile
          push: false
          provenance: false
          sbom: false
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.ref.name=${{ github.ref_name }}
            org.opencontainers.image.title=campaign-${{ matrix.service }}
          build-args: |
            GITHUB_PACKAGES_TOKEN=${{ secrets.GITHUB_TOKEN }}
